title: "Jamie Lab"
description: "Experiments. Networks. Homelab. Code."
markdown: kramdown
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: "/:name/"

  - scope:
      type: posts
    values:
      layout: post
      permalink: "/blog/:year/:month/:day/:title/"

