title: "Jamie Lab"
description: "Experiments. Networks. Homelab. Code."
url: "https://jamielab.me"
baseurl: ""
markdown: kramdown
excerpt_separator: "<!--more-->"

collections:
  notes:
    output: true
    permalink: /notes/:name/
  projects:
    output: true
    permalink: /projects/:name/
  pages:
    output: true

defaults:
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: "/:name/"

  - scope:
      type: posts
    values:
      layout: post
      permalink: "/blog/:year/:month/:day/:title/"

  - scope:
      type: notes
    values:
      layout: default

  - scope:
      type: projects
    values:
      layout: default

